"""add post description and documents

Revision ID: 1db5c46d1764
Revises: add_refund_fields
Create Date: 2026-06-12 21:42:00.521996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db5c46d1764'
down_revision: Union[str, Sequence[str], None] = 'add_refund_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('rules', sa.Text(), nullable=True, comment='场地规则'))
    op.add_column('clubs', sa.Column('documents', sa.JSON(), nullable=True, comment='PDF文件列表 [{name, url, size}]'))
    op.add_column('match_posts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('match_posts', sa.Column('documents', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('ntrp_level', sa.DECIMAL(precision=2, scale=1), nullable=True, comment='NTRP网球等级'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ntrp_level')
    op.drop_column('match_posts', 'documents')
    op.drop_column('match_posts', 'description')
    op.drop_column('clubs', 'documents')
    op.drop_column('clubs', 'rules')
    # ### end Alembic commands ###
