"""sync schema with models

Revision ID: 4ceb4203e64e
Revises: 1db5c46d1764
Create Date: 2026-06-18 16:49:12.509062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ceb4203e64e'
down_revision: Union[str, Sequence[str], None] = '1db5c46d1764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_orders', sa.Column('prepay_id', sa.String(length=64), nullable=True))
    op.add_column('booking_orders', sa.Column('prepay_id_created_at', sa.DateTime(), nullable=True))
    op.add_column('booking_orders', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('booking_orders', 'slot_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('booking_orders', 'status',
               existing_type=mysql.ENUM('pending', 'paid', 'cancelled', 'refunding', 'refunded', 'completed'),
               nullable=False)
    op.drop_index('order_no', table_name='booking_orders')
    op.create_index(op.f('ix_booking_orders_order_no'), 'booking_orders', ['order_no'], unique=True)
    op.add_column('club_members', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('club_members', 'role',
               existing_type=mysql.ENUM('owner', 'admin'),
               nullable=False)
    op.alter_column('clubs', 'split_ratio',
               existing_type=mysql.DECIMAL(precision=4, scale=3),
               nullable=False)
    op.alter_column('clubs', 'status',
               existing_type=mysql.ENUM('active', 'inactive'),
               nullable=False)
    op.add_column('match_posts', sa.Column('approval_required', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('match_posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('match_posts', 'status',
               existing_type=mysql.ENUM('open', 'closed', 'full'),
               nullable=False)
    op.add_column('match_registrations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('match_registrations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('match_registrations', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected'),
               nullable=False)
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('refund_records', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('refund_records', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('refund_records', sa.Column('fail_reason', sa.String(length=512), nullable=True))
    op.add_column('refund_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('refund_records', 'status',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.create_index('idx_refund_status_scheduled', 'refund_records', ['status', 'scheduled_at'], unique=False)
    op.add_column('settlement_records', sa.Column('out_order_no', sa.String(length=64), nullable=True))
    op.add_column('settlement_records', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('settlement_records', sa.Column('scheduled_at', sa.DateTime(), nullable=False))
    op.add_column('settlement_records', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('settlement_records', 'split_ratio',
               existing_type=mysql.DECIMAL(precision=4, scale=3),
               nullable=False)
    op.alter_column('settlement_records', 'status',
               existing_type=mysql.ENUM('pending', 'processing', 'completed', 'failed'),
               nullable=False)
    op.create_index('idx_settlement_status_scheduled', 'settlement_records', ['status', 'scheduled_at'], unique=False)
    op.create_unique_constraint(None, 'settlement_records', ['out_order_no'])
    op.add_column('tournament_registrations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tournament_registrations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tournament_registrations', 'status',
               existing_type=mysql.ENUM('registered', 'confirmed', 'cancelled'),
               nullable=False)
    op.add_column('tournaments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tournaments', 'lock_venue',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('tournaments', 'current_participants',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'entry_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('tournaments', 'status',
               existing_type=mysql.ENUM('draft', 'open', 'ongoing', 'finished', 'cancelled'),
               nullable=False)
    op.add_column('venue_time_slots', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('venue_time_slots', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('venue_time_slots', 'status',
               existing_type=mysql.ENUM('available', 'locked', 'booked', 'maintenance'),
               nullable=False)
    op.add_column('venues', sa.Column('opening_time', sa.Time(), nullable=False, server_default=sa.text("'08:00:00'")))
    op.add_column('venues', sa.Column('closing_time', sa.Time(), nullable=False, server_default=sa.text("'22:00:00'")))
    op.add_column('venues', sa.Column('slot_interval_minutes', sa.Integer(), nullable=False, server_default=sa.text('60')))
    op.add_column('venues', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('venues', 'max_capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('venues', 'status',
               existing_type=mysql.ENUM('active', 'maintenance', 'closed'),
               nullable=False)
    op.alter_column('venues', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('venues', 'status',
               existing_type=mysql.ENUM('active', 'maintenance', 'closed'),
               nullable=True)
    op.alter_column('venues', 'max_capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('venues', 'updated_at')
    op.drop_column('venues', 'slot_interval_minutes')
    op.drop_column('venues', 'closing_time')
    op.drop_column('venues', 'opening_time')
    op.alter_column('venue_time_slots', 'status',
               existing_type=mysql.ENUM('available', 'locked', 'booked', 'maintenance'),
               nullable=True)
    op.drop_column('venue_time_slots', 'updated_at')
    op.drop_column('venue_time_slots', 'created_at')
    op.alter_column('tournaments', 'status',
               existing_type=mysql.ENUM('draft', 'open', 'ongoing', 'finished', 'cancelled'),
               nullable=True)
    op.alter_column('tournaments', 'entry_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('tournaments', 'current_participants',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('tournaments', 'lock_venue',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('tournaments', 'updated_at')
    op.alter_column('tournament_registrations', 'status',
               existing_type=mysql.ENUM('registered', 'confirmed', 'cancelled'),
               nullable=True)
    op.drop_column('tournament_registrations', 'updated_at')
    op.drop_column('tournament_registrations', 'created_at')
    op.drop_constraint(None, 'settlement_records', type_='unique')
    op.drop_index('idx_settlement_status_scheduled', table_name='settlement_records')
    op.alter_column('settlement_records', 'status',
               existing_type=mysql.ENUM('pending', 'processing', 'completed', 'failed'),
               nullable=True)
    op.alter_column('settlement_records', 'split_ratio',
               existing_type=mysql.DECIMAL(precision=4, scale=3),
               nullable=True)
    op.drop_column('settlement_records', 'updated_at')
    op.drop_column('settlement_records', 'scheduled_at')
    op.drop_column('settlement_records', 'retry_count')
    op.drop_column('settlement_records', 'out_order_no')
    op.drop_index('idx_refund_status_scheduled', table_name='refund_records')
    op.alter_column('refund_records', 'status',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.drop_column('refund_records', 'updated_at')
    op.drop_column('refund_records', 'fail_reason')
    op.drop_column('refund_records', 'scheduled_at')
    op.drop_column('refund_records', 'retry_count')
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('notifications', 'updated_at')
    op.alter_column('match_registrations', 'status',
               existing_type=mysql.ENUM('pending', 'approved', 'rejected'),
               nullable=True)
    op.drop_column('match_registrations', 'updated_at')
    op.drop_column('match_registrations', 'created_at')
    op.alter_column('match_posts', 'status',
               existing_type=mysql.ENUM('open', 'closed', 'full'),
               nullable=True)
    op.drop_column('match_posts', 'updated_at')
    op.drop_column('match_posts', 'approval_required')
    op.alter_column('clubs', 'status',
               existing_type=mysql.ENUM('active', 'inactive'),
               nullable=True)
    op.alter_column('clubs', 'split_ratio',
               existing_type=mysql.DECIMAL(precision=4, scale=3),
               nullable=True)
    op.alter_column('club_members', 'role',
               existing_type=mysql.ENUM('owner', 'admin'),
               nullable=True)
    op.drop_column('club_members', 'created_at')
    op.drop_index(op.f('ix_booking_orders_order_no'), table_name='booking_orders')
    op.create_index('order_no', 'booking_orders', ['order_no'], unique=True)
    op.alter_column('booking_orders', 'status',
               existing_type=mysql.ENUM('pending', 'paid', 'cancelled', 'refunding', 'refunded', 'completed'),
               nullable=True)
    op.alter_column('booking_orders', 'slot_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_column('booking_orders', 'updated_at')
    op.drop_column('booking_orders', 'prepay_id_created_at')
    op.drop_column('booking_orders', 'prepay_id')
    # ### end Alembic commands ###
