"""add price column to match_posts

Revision ID: 66096adfc14a
Revises: aafa085649f4
Create Date: 2026-06-19 23:11:55.583344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66096adfc14a'
down_revision: Union[str, Sequence[str], None] = 'aafa085649f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_posts', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='人均费用'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_posts', 'price')
    # ### end Alembic commands ###
