"""add booking_order slot_ids

Revision ID: aafa085649f4
Revises: 4ceb4203e64e
Create Date: 2026-06-19 14:05:47.227491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafa085649f4'
down_revision: Union[str, Sequence[str], None] = '4ceb4203e64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_orders', sa.Column('slot_ids', sa.JSON(), nullable=True, comment='选中的所有连续时段 ID 列表 [id1, id2, ...]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_orders', 'slot_ids')
    # ### end Alembic commands ###
